"""
doc_generator.py — Automatic Dataset Documentation Generator
=============================================================

Produces a Markdown 'dataset card' including:
    - Schema summary
    - Feature descriptions
    - Statistical profile
    - Privacy assessment
    - Data quality notes
    - Usage guidelines
"""

from __future__ import annotations
import logging as _logging
_log = _logging.getLogger(__name__)
import json, os, sys
from datetime import datetime
from typing import Any, Dict, List, Optional


def generate_dataset_card(
    baseline: Dict[str, Any],
    leakage: Optional[Dict[str, Any]] = None,
    scan_report: Optional[Dict[str, Any]] = None,
    attack_report: Optional[Dict[str, Any]] = None,
    graph: Optional[Dict[str, Any]] = None,
    dataset_name: Optional[str] = None,
) -> str:
    """
    Generate a comprehensive Markdown dataset card.
    
    Parameters:
        baseline: Baseline statistics from baseline.py
        leakage: Leakage analysis from leakage_bridge.py
        scan_report: PII scan from data_scanner.py
        attack_report: Attack simulation from attack_simulator.py
        graph: Knowledge graph from knowledge_graph.py
        dataset_name: Optional name override
    
    Returns:
        Markdown string
    """
    meta = baseline.get("meta", {})
    columns = baseline.get("columns", {})
    correlations = baseline.get("correlations", {})
    
    num_cols = columns.get("numeric", {})
    cat_cols = columns.get("categorical", {})
    all_cols = {**num_cols, **cat_cols}
    
    name = dataset_name or meta.get("dataset_source", "Dataset")
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    
    lines: List[str] = []
    
    # ── Header ────────────────────────────────────────────────────────
    lines.append(f"# 📋 Dataset Card: {name}")
    lines.append("")
    lines.append(f"> Auto-generated by AutoMate Privacy Platform on {generated_at}")
    lines.append("")
    
    # ── Overview ──────────────────────────────────────────────────────
    lines.append("## 📊 Overview")
    lines.append("")
    lines.append(f"| Property | Value |")
    lines.append(f"|----------|-------|")
    lines.append(f"| **Source** | {name} |")
    lines.append(f"| **Rows** | {meta.get('row_count', 'N/A'):,} |" if isinstance(meta.get('row_count'), (int, float)) else f"| **Rows** | {meta.get('row_count', 'N/A')} |")
    lines.append(f"| **Columns** | {meta.get('column_count', len(all_cols))} |")
    lines.append(f"| **Numeric Features** | {len(num_cols)} |")
    lines.append(f"| **Categorical Features** | {len(cat_cols)} |")
    
    fp = meta.get("dataset_fingerprint")
    if fp:
        lines.append(f"| **Fingerprint** | `{str(fp)[:16]}…` |")
    lines.append("")
    
    # ── Schema ────────────────────────────────────────────────────────
    lines.append("## 🏗️ Schema")
    lines.append("")
    lines.append("| Column | Type | Null % | Unique | Min | Max | Mean |")
    lines.append("|--------|------|--------|--------|-----|-----|------|")
    
    for col, stats in num_cols.items():
        null_pct = f"{stats.get('null_ratio', 0) * 100:.1f}%" if stats.get("null_ratio") is not None else "—"
        uniq = stats.get("unique_count", "—")
        mn = f"{stats['min']:.2f}" if stats.get("min") is not None else "—"
        mx = f"{stats['max']:.2f}" if stats.get("max") is not None else "—"
        mean = f"{stats['mean']:.2f}" if stats.get("mean") is not None else "—"
        lines.append(f"| {col} | numeric | {null_pct} | {uniq} | {mn} | {mx} | {mean} |")
    
    for col, stats in cat_cols.items():
        null_pct = f"{stats.get('null_ratio', 0) * 100:.1f}%" if stats.get("null_ratio") is not None else "—"
        uniq = stats.get("unique_count", "—")
        lines.append(f"| {col} | categorical | {null_pct} | {uniq} | — | — | — |")
    
    lines.append("")
    
    # ── Correlations ──────────────────────────────────────────────────
    pearson = correlations.get("numeric_pearson", {})
    strong_corrs = [(k, v) for k, v in pearson.items() if abs(v) > 0.5]
    if strong_corrs:
        lines.append("## 🔗 Notable Correlations")
        lines.append("")
        lines.append("| Column Pair | Pearson r | Strength |")
        lines.append("|-------------|-----------|----------|")
        for key, val in sorted(strong_corrs, key=lambda x: -abs(x[1]))[:10]:
            pair = key.replace("__", " ↔ ")
            strength = "🔴 Strong" if abs(val) > 0.8 else "🟡 Moderate"
            lines.append(f"| {pair} | {val:.3f} | {strength} |")
        lines.append("")
    
    # ── Data Quality ──────────────────────────────────────────────────
    lines.append("## 🔍 Data Quality")
    lines.append("")
    
    high_null_cols = [(c, s.get("null_ratio", 0)) for c, s in all_cols.items() 
                      if s.get("null_ratio", 0) > 0.05]
    if high_null_cols:
        lines.append("### Missing Data")
        lines.append("")
        for col, ratio in sorted(high_null_cols, key=lambda x: -x[1]):
            bar = "█" * int(ratio * 20) + "░" * (20 - int(ratio * 20))
            lines.append(f"- **{col}**: {ratio*100:.1f}% missing `{bar}`")
        lines.append("")
    else:
        lines.append("✅ No columns have significant missing data (>5%).")
        lines.append("")
    
    # ── Privacy Assessment ────────────────────────────────────────────
    if leakage:
        lines.append("## 🔒 Privacy Assessment")
        lines.append("")
        
        ps = leakage.get("privacy_score")
        risk = leakage.get("risk_level", "unknown")
        mi_auc = leakage.get("membership_inference_auc")
        dup_rate = leakage.get("duplicates_rate")
        drift = leakage.get("statistical_drift")
        
        risk_icon = "🟢" if risk == "low" else "🟡" if risk == "warning" else "🔴"
        
        lines.append(f"| Metric | Value | Assessment |")
        lines.append(f"|--------|-------|------------|")
        if ps is not None:
            lines.append(f"| Privacy Score | {ps*100:.0f}/100 | {'✅ Good' if ps > 0.7 else '⚠️ Needs attention'} |")
        if mi_auc is not None:
            lines.append(f"| MI-AUC | {mi_auc:.4f} | {'✅ Resistant' if mi_auc < 0.6 else '⚠️ Vulnerable'} |")
        if dup_rate is not None:
            lines.append(f"| Duplicate Rate | {dup_rate*100:.1f}% | {'✅ Low' if dup_rate < 0.05 else '⚠️ High'} |")
        if drift:
            lines.append(f"| Drift Level | {drift} | {risk_icon} {risk.title()} |")
        lines.append("")
        
        # Threats
        threats = leakage.get("threat_details") or leakage.get("top_threats") or []
        if threats:
            lines.append("### Detected Threats")
            lines.append("")
            for t in threats:
                sev = t.get("severity", "unknown")
                sev_icon = "🔴" if sev == "high" else "🟡" if sev == "medium" else "🟢"
                lines.append(f"- {sev_icon} **{t.get('name', 'Unknown')}** ({sev}) — {t.get('description', '')}")
            lines.append("")
    
    # ── PII Scan ──────────────────────────────────────────────────────
    if scan_report:
        lines.append("## 🛡️ PII & Sensitivity Scan")
        lines.append("")
        n_pii = len(scan_report.get("pii_findings", []))
        n_sec = len(scan_report.get("secrets", []))
        n_sen = len(scan_report.get("sensitive_content", []))
        risk_score = scan_report.get("risk_score", 0)
        
        lines.append(f"| Finding Type | Count |")
        lines.append(f"|-------------|-------|")
        lines.append(f"| PII | {n_pii} |")
        lines.append(f"| Secrets | {n_sec} |")
        lines.append(f"| Sensitive Content | {n_sen} |")
        lines.append(f"| **Risk Score** | **{risk_score:.0f}/100** |")
        
        hrcs = scan_report.get("high_risk_columns", [])
        if hrcs:
            lines.append(f"\n⚠️ **High-risk columns**: {', '.join(f'`{c}`' for c in hrcs)}")
        lines.append("")
    
    # ── Attack Simulation ─────────────────────────────────────────────
    if attack_report:
        lines.append("## ⚔️ Attack Simulation Results")
        lines.append("")
        lines.append(f"**Overall Vulnerability**: {attack_report.get('overall_vulnerability', 'unknown').upper()}")
        lines.append("")
        
        for r in attack_report.get("results", []):
            icon = "❌" if r.get("success") else "✅"
            lines.append(f"- {icon} **{r.get('attack_name', 'Unknown')}**: {r.get('description', '')}")
        
        recs = attack_report.get("recommendations", [])
        if recs:
            lines.append("")
            lines.append("### Recommendations")
            for rec in recs:
                lines.append(f"- 💡 {rec}")
        lines.append("")
    
    # ── Knowledge Graph ───────────────────────────────────────────────
    if graph:
        entities = graph.get("entities", [])
        if entities:
            lines.append("## 🕸️ Detected Entities")
            lines.append("")
            for e in entities:
                lines.append(f"- **{e.title()}**")
            lines.append("")
    
    # ── Usage Guidelines ──────────────────────────────────────────────
    lines.append("## 📝 Usage Guidelines")
    lines.append("")
    lines.append("- This dataset card was auto-generated from pipeline analysis results.")
    lines.append("- Review all privacy findings before using this dataset in production.")
    lines.append("- Consider anonymization for columns flagged with PII findings.")
    lines.append("- Re-run analysis after any data transformations.")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by AutoMate Privacy Platform · {generated_at}*")
    
    return "\n".join(lines)


# ============================================================
# CLI
# ============================================================

def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(description="Dataset Documentation Generator")
    p.add_argument("--baseline", required=True, help="Path to baseline JSON")
    p.add_argument("--leakage", default=None, help="Path to leakage JSON")
    p.add_argument("--scan", default=None, help="Path to scan report JSON")
    p.add_argument("--attack", default=None, help="Path to attack report JSON")
    p.add_argument("--graph", default=None, help="Path to knowledge graph JSON")
    p.add_argument("--name", default=None, help="Dataset name")
    p.add_argument("--output", default=None, help="Output markdown path")
    args = p.parse_args(argv)

    def load_json(path):
        if not path or not os.path.exists(path):
            return None
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    baseline = load_json(args.baseline) or {}
    leakage = load_json(args.leakage)
    scan = load_json(args.scan)
    attack = load_json(args.attack)
    graph = load_json(args.graph)

    md = generate_dataset_card(
        baseline=baseline, leakage=leakage, scan_report=scan,
        attack_report=attack, graph=graph, dataset_name=args.name
    )

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(md)
        _log.info("doc_generator: card saved to %s", args.output)
    else:
        sys.stdout.write(md + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
